# Generated by Django 5.1.3 on 2024-12-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('market_cap', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('supply', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('rank', models.IntegerField(default=0)),
                ('percent_change_24h', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
        ),
    ]
