# Generated by Django 5.1.3 on 2024-12-14 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoritesCrypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_user', to='crypto.cryptocurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_cryptos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'crypto')},
            },
        ),
    ]
