# Generated by Django 5.1.3 on 2024-12-14 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaCategory',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='YogaPose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=100)),
                ('sanskrit_name', models.CharField(max_length=100)),
                ('translation_name', models.CharField(max_length=100)),
                ('pose_description', models.TextField()),
                ('pose_benefits', models.TextField()),
                ('url_svg_alt', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserFavoriteYogaPoses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_yoga_poses', to=settings.AUTH_USER_MODEL)),
                ('yoga_pose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_users', to='yoga.yogapose')),
            ],
            options={
                'unique_together': {('user', 'yoga_pose')},
            },
        ),
    ]
