# Generated by Django 5.1.3 on 2024-12-03 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_crypto', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
