# Generated by Django 5.1.3 on 2024-12-11 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_crypto', '0004_rename_create_at_post_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaPose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=100)),
                ('sanskrit_name', models.CharField(max_length=100)),
                ('translation_name', models.CharField(max_length=100)),
                ('pose_description', models.TextField()),
                ('pose_benefits', models.TextField()),
                ('url_svg_alt', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserFavoriteYogaPoses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_yoga_poses', to=settings.AUTH_USER_MODEL)),
                ('yoga_pose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_users', to='users_and_crypto.yogapose')),
            ],
            options={
                'unique_together': {('user', 'yoga_pose')},
            },
        ),
    ]
