# Generated by Django 5.1.3 on 2024-12-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_crypto', '0005_yogapose_userfavoriteyogaposes'),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaCategory',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
